---
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output_word") })
title: "Alklalinity Analysis"
output:
  officedown::rdocx_document:
    reference_docx: word_style_ref_01.docx
editor_options:
  chunk_output_type: console
#bibliography: references.bib
---

```{r knitter_options, include = FALSE}
# chunk header include = FALSE supresses code in the Word output
# chunk options supress warnings, messages and output in the Word output
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE)
```

```{r libraries}
library(tidyverse)
library(here)
library(janitor)
library(todor)
library(readxl)
library(fs)
```

```{r color-palette}
# A color-blind friendly palette :

cbPalette <- c("#E69F00","#56B4E9","#009E73",
               "#F0E442","#0072B2","#D55E00","#CC79A7")
```

```{r read-treatment-file}
d_treat <- read_csv(here("data", "example_alk", "treatment_data", "r1_treatment.csv")) %>%
  filter(!is.na(Unit)) %>%
  rename(unit = Unit,
         unit_number = UnitNumber,
         treat_start_date = StartDate,
         treat_end_date = EndDate,
         treatment_name = TreatmentName,
         temperature = Tempereture,
         ph = pH,
         additional_treament = AdditionalTreatmentA)
```

```{r read-alk-files}
d_alk <- dir_ls(here("data", "example_alk", "alk_data"), regexp = "xlsx") %>%
  map_dfr(read_excel) %>% 
  left_join(d_treat, by = c("unit", "unit_number")) %>%
  unite("unit_id", c(unit, unit_number), remove = FALSE)

```

```{r plot-variable-options}

plot_opts <- list( lab = unique(d_alk$alk_lab),
                      run_by = unique(d_alk$run_by),
                      experiment = unique(d_alk$experiment),
                      unit = unique(d_alk$unit),
                      unit_id = unique(d_alk$unit_id),
                      water_source = unique(d_alk$water_source),
                      water_type = unique(d_alk$water_type),
                      sample_set = unique(d_alk$sample_set),
                      date = unique(d_alk$date),
                      treatment = unique(d_alk$treatment_name))

```

```{r plot-filter-fun}

plot_filter <- function(d_alk){
  d_alk_filtered <- d_alk %>%
               filter(alk_lab %in% plot_opts$lab[],
                      run_by %in% plot_opts$run_by[],
                      experiment %in% plot_opts$experiment[],
                      unit %in% plot_opts$unit[],
                      unit_id %in% plot_opts$unit_id[],
                      water_source %in% plot_opts$water_source[],
                      water_type %in% plot_opts$water_type[],
                      sample_set %in% plot_opts$sample_set[],
                      date %in% plot_opts$date[],
                      treatment_name %in% plot_opts$treatment[])
  return(d_alk_filtered)
}


```

```{r}
plot_var_opts <- c("alk_lab", 
                 "run_by", 
                 "experiment", 
                 "unit", 
                 "unit_id", 
                 "water_source",
                 "water_type", 
                 "sample_set", 
                 "date", 
                 "treatment_name")

```


```{r plot}

alk_box_plot <- function(d_alk_filtered, plot_type = "box", plot_var_opts, x_axis_index, 
                         color_by_index, facet_by_index){
  # variables for testing
  # plot_type = "box"
  # x_axis_index <- c(4)
  # color_by_index <- c(6,7)
  # facet_by_index <- c(8)
  # d_alk_filtered <- plot_filter(d_alk)
  
  
  # add x-axis variable
  d_alk_plot  <- d_alk_filtered %>%
    unite(x_axis, plot_var_opts[x_axis_index], remove = FALSE)
  
  # return null default
  p <- NULL
  
  ### box plots
  if(plot_type == "box" & is.null(color_by_index) & is.null(facet_by_index)){
             p <- d_alk_plot %>%
                    ggplot(aes(x_axis, alkalinity)) +
                      geom_jitter(alpha = 0.5) +
                      geom_boxplot()
  }
  
  if(plot_type == "box" & !is.null(color_by_index) & is.null(facet_by_index)){
              p <-  d_alk_plot %>%
                        unite(color_by, plot_var_opts[color_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_jitter(aes(color = color_by), alpha = 0.5) +
                          geom_boxplot(aes(color = color_by)) +
                          scale_colour_discrete(paste(plot_var_opts[color_by_index], collapse = "_"))
  }
    
  if(plot_type == "box" & is.null(color_by_index) & !is.null(facet_by_index)){
              p <-  d_alk_plot %>%
                        unite(facet_by, plot_var_opts[facet_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_jitter(alpha = 0.5) +
                          geom_boxplot() +
                          facet_wrap(vars(facet_by))
  }  
              
  if(plot_type == "box" & !is.null(color_by_index) & !is.null(facet_by_index)){
                p <-  d_alk_plot %>%
                        unite(color_by, plot_var_opts[color_by_index], remove = FALSE) %>%
                        unite(facet_by, plot_var_opts[facet_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_jitter(aes(color = color_by), alpha = 0.5) +
                          geom_boxplot(aes(color = color_by)) +
                          facet_wrap(vars(facet_by)) + 
                          scale_colour_discrete(paste(plot_var_opts[color_by_index], collapse = "_"))
  }
  
  
  ### scatter plots
  if(plot_type == "scatter" & is.null(color_by_index) & is.null(facet_by_index)){
             p <- d_alk_plot %>%
                    ggplot(aes(x_axis, alkalinity)) +
                      geom_point() +
                      geom_boxplot()
  }
  
  if(plot_type == "scatter" & !is.null(color_by_index) & is.null(facet_by_index)){
              p <-  d_alk_plot %>%
                        unite(color_by, plot_var_opts[color_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_point(aes(color = color_by)) +
                          scale_colour_discrete(paste(plot_var_opts[color_by_index], collapse = "_"))
  }
    
  if(plot_type == "scatter" & is.null(color_by_index) & !is.null(facet_by_index)){
              p <-  d_alk_plot %>%
                        unite(facet_by, plot_var_opts[facet_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_point() +
                          facet_wrap(vars(facet_by))
  }  
              
  if(plot_type == "scatter" & !is.null(color_by_index) & !is.null(facet_by_index)){
                p <-  d_alk_plot %>%
                        unite(color_by, plot_var_opts[color_by_index], remove = FALSE) %>%
                        unite(facet_by, plot_var_opts[facet_by_index], remove = FALSE) %>%
                        ggplot(aes(x_axis, alkalinity)) +
                          geom_point(aes(color = color_by)) +
                          facet_wrap(vars(facet_by)) + 
                          scale_colour_discrete(paste(plot_var_opts[color_by_index], collapse = "_"))
  }

  #set attributes common to all plots
  p <- p + 
    xlab(paste(plot_var_opts[x_axis_index], collapse = "_")) +
    theme_bw(base_size = 16)
    
  return(p)
}


```


```{r}
alk_box_plot(plot_filter(d_alk), "box", plot_var_opts, c(4), c(6,7), c(8))
alk_box_plot(plot_filter(d_alk), "box", plot_var_opts, c(4), NULL, c(8))
alk_box_plot(plot_filter(d_alk), "box", plot_var_opts, c(4), c(6,7), NULL)
alk_box_plot(plot_filter(d_alk), "box", plot_var_opts, c(4), NULL, NULL)

alk_box_plot(plot_filter(d_alk), "scatter", plot_var_opts, c(9), c(6,7), c(8))
alk_box_plot(plot_filter(d_alk), "scatter", plot_var_opts, c(9), NULL, c(8))
alk_box_plot(plot_filter(d_alk), "scatter", plot_var_opts, c(9), c(6,7), NULL)
alk_box_plot(plot_filter(d_alk), "scatter", plot_var_opts, c(9), NULL, NULL)


alk_box_plot(plot_filter(d_alk), "scatter", plot_var_opts, c(9), c(6,7), c(8))


```


